Diriian/ToME-Fr

Module Principal
Trad section "game/modules/tome/data/chats/last-hope-melinda-father.lua"
+
ajout d'une ligne pour la cohérence du formatage
=> Trad dirian

Module Principal
Trad et Test
data/chats/ring-of-blood-win.lua"
data/chats/sage-kitty.lua"
data/chats/shadow-crypt-yeek-clone.lua"
data/chats/shertul-fortress-butler.lua"
=> Update Module Principal

Module Principal
Trad et Test + misc
data/chats/slasul.lua"
data/chats/sorcerer-end.lua"
data/chats/sorcerer-fight.lua"
data/chats/tannen.lua"
=> data/chats/slasul.lua" data/chats/sorcerer-end.lua" data/chats/sorcerer-fight.lua" data/chats/tannen.lua"

Menu Principal
Modification du header du fichier du menu principal pour le tutoriel de la section "débuter" du discord
=> Modification mineure pour faire un tutoriel pour le discord

Menu Principal, Module Principal
Test ok... reste un problème de taille de bouton dynamique dans le menu du jeu.
=> Mise à jour de la traduction du fichier engine

Menu Principal, Module Principal
trad et test
/zemekkys-done.lua
/zemekkys-start-chronomancers.lua
/zemekkys.lua
+
misc
=> trad et test + misc

mod-tome.lua
=> Trad et Test

mod-tome.lua
AdvanceActor.lua
AdvanceZones.lua
AlterFaction.lua
ChangeZone.lua
CreateItem.lua
CreateTrap.lua
DebugMain.lua
Endgamify.lua
GrantQuest.lua
PlotTalent.lua
RandomActor.lua
RandomObject.lua
SpawnEvent.lua
=> Trad Mode dev (addon Dev)

mod-tome.lua
SummonCreature.lua
Behavior.lua
Talents.lua
CommonData.lua
Shimmer.lua
ShimmerDemo.lua
ShimmerOther.lua
ShimmerOutfits.lua
ShimmerRemoveSustains.lua
ChronomancyContingency.lua
ChronomancyEmpower.lua
ChronomancyExtension.lua
ChronomancyMatrix.lua
ChronomancyQuicken.lua
MagicalCombatArcaneCombat.lua
corrections
=> Shimmer, spellbinding et arcane combat(selection des sorts), divers

mod-tome.lua
UserChatExtension.lua
World.lua
WorldNPC.lua
Arena.lua
HighPeakFinal.lua
ValleyMoon.lua
misc
=> arena + liens dans le chat

engine.lua, mod-boot.lua, mod-tome.lua, tome-items-vault.lua
=> Passage des fichiers en 1.7.3

mod-tome.lua, tome-items-vault.lua
=> Tous les succès

mod-tome.lua
=> Derth Alchemist + corrections

mod-tome.lua
=> Alchemist quests

mod-tome.lua
Angolwen Leader & Staff Training
=> Angolwen Leader & Staff Training

mod-tome.lua
=> Antimagic end & Ardhungol

mod-tome.lua
=> Arene 1ere partie

engine.lua, mod-boot.lua, mod-tome.lua, tome-items-vault.lua
=> Passage en 1.7.4

mod-tome.lua
=> Arene, 2eme partie

mod-tome.lua
Artifice, assassin lord, avatar of distant dun
=> Artifice, assassin lord, avatar of distant dun

mod-tome.lua
elisa
fallen-aeryn
gates-of-morning
golbug
jewelry-store
misc
=> Elisa, Aeryn, Golbug, Limmir

mod-tome.lua
sorcerer-end
sorcerer-fight
zemekkys
zigur
zoisla
=> Sorcerer, Zemekkys, Zigur, & Zoisla

engine.lua, mod-tome.lua
=> damage type & misc

mod-tome.lua
patrrouilles(fin), events(debut)
+ misc
=> patrrouilles(fin), events(debut)

mod-tome.lua
=> npcs 1ere partie

mod-tome.lua
=> npcs 2eme partie

mod-tome.lua
=> npcs 3eme partie

mod-tome.lua
=> npcs 4eme et derniere partie

mod-tome.lua
=> artifacts 1ere partie

mod-tome.lua
artifacts & objets 2eme partie
=> artifacts & objets 2eme partie

mod-tome.lua
artifacts & objets 3eme partie
=> artifacts & objets 3eme partie

mod-tome.lua
=> textes 1ere partie

mod-tome.lua
=> textes partie 2

mod-tome.lua
=>  textes partie 3 (fin)

mod-tome.lua
=> /timed_effects/floor
